{% set name = "sed" %}
{% set version = "4.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: 6e226b732e1cd739464ad6862bd1a1aba42d7982922da7a53519631d24975181

build:
  number: 0 
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
    - libtool
  host:
    - gettext >=0.19.2  # [osx]
  run:
    - gettext >=0.19.2  # [osx]

test:
  commands:
    - test -f "${PREFIX}/bin/sed"
    - sed --version

about:
  home: https://www.gnu.org/software/sed
  license: GPL-3
  license_family: GPL
  license_file: COPYING
  summary: sed (stream editor) is a non-interactive command-line text editor.
  description: |
    sed is commonly used to filter text, i.e., it takes text input, performs
    some operation (or set of operations) on it, and outputs the modified text.
    sed is typically used for extracting part of a file using pattern matching
    or substituting multiple occurrences of a string within a file.
  dev_url: https://cgit.git.savannah.gnu.org/cgit/sed.git
  doc_url: https://www.gnu.org/software/sed/manual/sed.html
extra:
  recipe-maintainers:
    - mingwandroid
    - tfors
