travis:
  secure:
    BINSTAR_TOKEN: u2C3Q8BI4pTMZui/yG5YeceLD+L2+iuOBFrqt4Nb15v1NyZF8FeoO/LusNxIvDt7exFI1gpe9gcN8bOsZ9Szmtx132AoElALJmeFtje5D9jpssCOzETTycAMaLsxqAqGITv/nKn3+GzGljIbuvqaMjHs372cMy1ztsKOI/bJYAucp+FSw1p9Lfgw3BIs0XbZ3532bQYNmu5XDxFGbzIes5g1kghySMQzgxKptLDEb5MP0QmDfaCnLdqAGsL3qFL8C3DnBjDicvZMfGwPopLFv/k/rEPAr/laz5aZEXINPEW8ZbeLrpbhSnLMqJpyGPeuuVpgqYsoib+ObWKvJ2NjbIbDQpjgdBzoGidrTYN4xK6T7Hq5jjZCoS2gVcuDNAYesFHCaT7UIziLVGJMrcj31pbMm0LnM2FTUmom+9o52zAa5gQ3FiVxf2NBB5+a3RvWfXgcVVE+qRLy5g7+X8N9ehy4emFYEWw3d4PEzcu9peGENALLKz2Wv1t+ERlHWoSHYAqDjO0EU+ruJRixn4nx4D4HTMqiFtPlEnbZWu5u151ihoiPNR+rz8et4bVRMNHBxw+dILKf8/YzrWaaqs1qZJD5m3GmG7pS5SiiI72AJHoYnvs++DZgPsCWi1uYybLDR+f8J0Q1kyOmhQ95w6BFUigjUeO6GSoUOSW3zyj3OW4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
