travis:
  secure:
    BINSTAR_TOKEN: C9rVaGZYks/gc7RW4bG2CxbxZLYcBbXhxarfc/rjLnNlAr8S24Ot+gesdT9n6oLAI6vaEe38nJ+Re5nmvrWkQiDahPZLYnKNwH5d6sXU+jSg9/Cm8T8wbh3QgXVkAIFpCgzfbdMBo+NRhpUVz/O4ia1OnU4kT2PmgT9KIRdm9qZGk8Xi9yeLtmqtglFFq3VbKjPvFNUJLXSKFY9fzeuuc4soTd64l3BpPLvXFgYdP+tODqqwyaDW67GrMJWYigKw1oVUdFuGQqecej9pVgzJSe6SpP3+sabi0Zahq5QucXrMpYDSkxlRbAQ+E8jgBk4zdgGfuaJmgRJGxP27XaUH09iORe2GxsT5+TNEDLet+wuPsRasEprgYYxUvec5Yi5lA351CaDh1hbNaEMbPb25cam2tZm4RdDDAuBUiTxSNVb3IA/slf7ysioYufzBcBWSg4NCqPX66pAKWd7fiQEXbM+oky+XvAWhBIZZK68LudwNw6cHVzc3IDcSYv+LzWbCYLsPeKGyah+G7XYcy8fiCb/bki1hKt7XFVt+ZWDAqpgoM+i2lM/UbYWv4itI87Fi03GLalKZe8cXW9WIa+dqQAHFfjp4AZtWHL1rJgr7NKAFdlUhRHFd/bfr6/HSNGlrZO3tAyP8RfjyYP+QYtpzEa5foQnljJ5inJaRcI486ZM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
